### ISSUE TITLE
SyntaxError in AlbumSelection

### ISSUE THREAD

**Issue by JonRheaSr** [SharieRhea/TrackTagger#1]
When I run the program and it tried to import AlbumSelection.py I get this error:

```
Traceback (most recent call last):
  File "/track_tagger-main/TrackTagger.py", line 14, in <module>
    from AlbumSelection import AlbumSelection
  File "/track_tagger-main/AlbumSelection.py", line 50
    radio_button = ctk.CTkRadioButton(self.sub_frame, text = f"{albums[i]["name"]} by {albums[i]["artist"]}", variable = self.album_index, value = i)
                                                                           ^^^^
SyntaxError: f-string: unmatched '['
```

I solved it by replacing the double quotes around "name" and "artist" with single quotes

**Comment by SharieRhea** [comment]
Closed with commit 975843b4ce931faa92e4f8c821fbbc6e70999c4a. 
Interesting that double quotes inside an f-string didn't cause issues for me, but it was certainly bad practice.
